### ISSUE TITLE
Missing header file

### ISSUE THREAD

**Issue by zzy-learner** [rummanwaqar/underwater-localization#1]
When compiling, error: missing au_ The header file for the core. I have carefully reviewed all the packages and found that there is indeed no such file. Could you please supplement it? Thank you very much
![image](https://user-images.githubusercontent.com/62506270/228711599-29eaadf0-05d3-4c38-b05e-2172a98cb535.png)

**Comment by rummanwaqar** [comment]
Sorry the messages in au_core are part of a closed source robot I worked on. I have no longer access to it so I won't be able to help you here.

**Comment by zzy-learner** [comment]
OK, thank you for your reply. I will try to improve the relevant parts myself. The overall code framework is complete and has provided me with a great help.
